# æœºåœºè®¢é˜…
proxy-providers:
  å†²æµªäº‘:
    type: http # http çš„ path å¯ç©ºç½®ï¼Œé»˜è®¤å‚¨å­˜è·¯å¾„ä¸º homedir çš„ proxies æ–‡ä»¶å¤¹ï¼Œæ–‡ä»¶åä¸º url çš„ md5
    url: ""
    interval: 86400
    proxy: DIRECT
    header:
      User-Agent:
      - "Clash/v1.18.0"
      - "mihomo/1.18.3"
    health-check:
      enable: true
      interval: 600
      # lazy: true
      url: https://cp.cloudflare.com/generate_204
    override: # è¦†å†™èŠ‚ç‚¹åŠ è½½æ—¶çš„ä¸€äº›é…ç½®é¡¹
      # skip-cert-verify: true
      # udp: true
      # down: "50 Mbps"
      # up: "10 Mbps"
      # dialer-proxy: proxy
      # interface-name: tailscale0
      # routing-mark: 233
      ip-version: ipv4-prefer
      # additional-prefix: "[provider1]"
      # additional-suffix: "test"
      # # åå­—æ›¿æ¢ï¼Œæ”¯æŒæ­£åˆ™è¡¨è¾¾å¼
      # proxy-name:
      #   - pattern: "test"
      #     target: "TEST"
      #   - pattern: "IPLC-(.*?)å€"
      #     target: "iplc x $1"

# å…¨å±€é…ç½®
mixed-port: 10801 # HTTP(S) å’Œ SOCKS ä»£ç†æ··åˆç«¯å£
allow-lan: true # å…è®¸å±€åŸŸç½‘è¿æ¥
bind-address: "*" # ç»‘å®š IP åœ°å€ï¼Œä»…ä½œç”¨äº allow-lan ä¸º trueï¼Œ'*'è¡¨ç¤ºæ‰€æœ‰åœ°å€
tcp-concurrent: true
find-process-mode: off
mode: rule
log-level: warning # æ—¥å¿—ç­‰çº§ silent/error/warning/info/debug
ipv6: true # å¼€å¯ IPv6 æ€»å¼€å…³ï¼Œå…³é—­é˜»æ–­æ‰€æœ‰ IPv6 é“¾æ¥å’Œå±è”½ DNS è¯·æ±‚ AAAA è®°å½•
# interface-name: en0 # è®¾ç½®å‡ºå£ç½‘å¡
global-client-fingerprint: chrome # å¯é€‰ï¼š"chrome","firefox","safari","ios","random","none" options.
disable-keep-alive: false #ç›®å‰åœ¨androidç«¯å¼ºåˆ¶ä¸ºtrue
keep-alive-idle: 600
keep-alive-interval: 15
profile:
  store-selected: true  # å­˜å‚¨ select é€‰æ‹©è®°å½•
  store-fake-ip: true  # æŒä¹…åŒ– fake-ip

# geoæ•°æ®åº“
geox-url: #è‡ªå®šä¹‰ geodata url
  geoip: "https://fastly.jsdelivr.net/gh/MetaCubeX/meta-rules-dat@release/geoip.dat"
  geosite: "https://fastly.jsdelivr.net/gh/MetaCubeX/meta-rules-dat@release/geosite.dat"
  mmdb: "https://fastly.jsdelivr.net/gh/MetaCubeX/meta-rules-dat@release/geoip.metadb"
geo-auto-update: false # æ˜¯å¦è‡ªåŠ¨æ›´æ–° geodata
geo-update-interval: 24 # æ›´æ–°é—´éš”ï¼Œå•ä½ï¼šå°æ—¶

# æ§åˆ¶é¢æ¿
external-controller: 0.0.0.0:9090 # RESTful API ç›‘å¬åœ°å€
secret: "" # `Authorization:Bearer ${secret}`
external-ui: "/etc/mihomo/run/ui" # é…ç½® WEB UI ç›®å½•ï¼Œä½¿ç”¨ http://{{external-controller}}/ui è®¿é—®
# external-ui-name: xd
external-ui-url: "https://github.com/MetaCubeX/metacubexd/archive/refs/heads/gh-pages.zip" # ç›®å‰æ”¯æŒä¸‹è½½zip,tgzæ ¼å¼çš„å‹ç¼©åŒ…

# Tun é…ç½®
tun:
  enable: true
  stack: mixed # gvisor/mixed/system
  dns-hijack: ["any:53", "tcp://any:53"] # éœ€è¦åŠ«æŒçš„ DNS
  auto-detect-interface: true # è‡ªåŠ¨è¯†åˆ«å‡ºå£ç½‘å¡
  auto-route: true # é…ç½®è·¯ç”±è¡¨
  auto-redirect: false # è‡ªåŠ¨é…ç½® iptables ä»¥é‡å®šå‘ TCP è¿æ¥ã€‚ä»…æ”¯æŒ Linuxã€‚å¸¦æœ‰ auto-redirect çš„ auto-route ç°åœ¨å¯ä»¥åœ¨è·¯ç”±å™¨ä¸ŠæŒ‰é¢„æœŸå·¥ä½œï¼Œæ— éœ€å¹²é¢„ã€‚
  route-exclude-address-set: # å°†æŒ‡å®šè§„åˆ™é›†ä¸­çš„ç›®æ ‡ IP CIDR è§„åˆ™æ·»åŠ åˆ°é˜²ç«å¢™, åŒ¹é…çš„æµé‡å°†ç»•è¿‡è·¯ç”±, ä»…æ”¯æŒ Linuxï¼Œä¸”éœ€è¦ nftablesï¼Œ`auto-route` å’Œ `auto-redirect` å·²å¯ç”¨ã€‚
    - cn_ip

# å—…æ¢åŸŸå å¯é€‰é…ç½®
sniffer:
  enable: true
  override-destination: false
  sniff: # TLS å’Œ QUIC é»˜è®¤å¦‚æœä¸é…ç½® ports é»˜è®¤å—…æ¢ 443
    QUIC:
      ports: [443, 8443]
    TLS:
      ports: [443, 8443]
    HTTP: # éœ€è¦å—…æ¢çš„ç«¯å£ï¼Œé»˜è®¤å—…æ¢ 80
      ports: [80, 8080-8880]
      override-destination: true # å¯è¦†ç›– sniffer.override-destination
  force-domain: # å¼ºåˆ¶å¯¹æ­¤åŸŸåè¿›è¡Œå—…æ¢
    - +.v2ex.com
  skip-domain: # å¯¹å—…æ¢ç»“æœè¿›è¡Œè·³è¿‡
    - "rule-set:private_domain,cn_domain"

# DNS é…ç½®
dns:
  cache-algorithm: arc
  enable: true # å…³é—­å°†ä½¿ç”¨ç³»ç»Ÿ DNS
  prefer-h3: false # æ˜¯å¦å¼€å¯ DoH æ”¯æŒ HTTP/3ï¼Œå°†å¹¶å‘å°è¯•
  listen: 0.0.0.0:53 # å¼€å¯ DNS æœåŠ¡å™¨ç›‘å¬
  ipv6: true # false å°†è¿”å› AAAA çš„ç©ºç»“æœ
  ipv6-timeout: 300 # å•ä½ï¼šmsï¼Œå†…éƒ¨åŒæ ˆå¹¶å‘æ—¶ï¼Œå‘ä¸Šæ¸¸æŸ¥è¯¢ AAAA æ—¶ï¼Œç­‰å¾… AAAA çš„æ—¶é—´ï¼Œé»˜è®¤ 100ms
  # ç”¨äºè§£æ nameserverï¼Œfallback ä»¥åŠå…¶ä»– DNS æœåŠ¡å™¨é…ç½®çš„ï¼ŒDNS æœåŠ¡åŸŸå
  # åªèƒ½ä½¿ç”¨çº¯ IP åœ°å€ï¼Œå¯ä½¿ç”¨åŠ å¯† DNS
  default-nameserver:
    - 223.5.5.5
    - 114.114.114.114
    - 119.29.29.29
  enhanced-mode: fake-ip # or redir-host
  fake-ip-range: 198.18.0.1/16 # fake-ip æ± è®¾ç½®
  fake-ip-filter: # é…ç½®ä¸ä½¿ç”¨ fake-ip çš„åŸŸå
    - "rule-set:private_domain,cn_domain"
    - "rule-set:category_ntp,fakeip_filter"
  fake-ip-filter-mode: blacklist
  # use-hosts: true # æŸ¥è¯¢ hosts
  respect-rules: true # dnsè¿æ¥éµå®ˆè·¯ç”±è§„åˆ™ã€‚
  nameserver:
    - system
    - 223.5.5.5
    - 114.114.114.114
    - 119.29.29.29
  # å½“é…ç½® fallback æ—¶ï¼Œä¼šæŸ¥è¯¢ nameserver ä¸­è¿”å›çš„ IP æ˜¯å¦ä¸º CNï¼Œéå¿…è¦é…ç½®
  # å½“ä¸æ˜¯ CNï¼Œåˆ™ä½¿ç”¨ fallback ä¸­çš„ DNS æŸ¥è¯¢ç»“æœ
  # ç¡®ä¿é…ç½® fallback æ—¶èƒ½å¤Ÿæ­£å¸¸æŸ¥è¯¢
  fallback:
    - https://1.1.1.1/dns-query
    - https://dns.google/dns-query
    - https://dns.cloudflare.com/dns-query
  proxy-server-nameserver:  # ä¸“ç”¨äºèŠ‚ç‚¹åŸŸåè§£æçš„ DNS æœåŠ¡å™¨
    - system
    - 223.5.5.5
    - 114.114.114.114
    - 119.29.29.29
  direct-nameserver: # ä¸“ç”¨äºdirectå‡ºå£åŸŸåè§£æçš„ DNS æœåŠ¡å™¨
    - system://
    - 223.5.5.5
    - 114.114.114.114
    - 119.29.29.29
  # nameserver-policy:
  #   #   'www.baidu.com': '114.114.114.114'
  #   #   '+.internal.crop.com': '10.0.0.1'
  #   "geosite:cn,private,apple":
  #     - https://doh.pub/dns-query
  #     - https://dns.alidns.com/dns-query
proxies:
  - {name: ç›´è¿, type: direct}
pr: &pr {type: select, proxies: [ğŸš€ é»˜è®¤ä»£ç†, ğŸ”¯ é¦™æ¸¯æ•…è½¬, ğŸ”¯ æ—¥æœ¬æ•…è½¬, â™»ï¸ é¦™æ¸¯è‡ªåŠ¨, â™»ï¸ æ—¥æœ¬è‡ªåŠ¨, â™»ï¸ ç¾å›½è‡ªåŠ¨, â™»ï¸ è‡ªåŠ¨é€‰æ‹©, ğŸ‡­ğŸ‡° é¦™æ¸¯èŠ‚ç‚¹, ğŸ‡¯ğŸ‡µ æ—¥æœ¬èŠ‚ç‚¹, ğŸ‡ºğŸ‡² ç¾å›½èŠ‚ç‚¹, ğŸŒ å…¨éƒ¨èŠ‚ç‚¹, ç›´è¿]}
proxy-groups:
  - {name: ğŸš€ é»˜è®¤ä»£ç†, type: select, proxies: [ğŸ”¯ é¦™æ¸¯æ•…è½¬, ğŸ”¯ æ—¥æœ¬æ•…è½¬, â™»ï¸ é¦™æ¸¯è‡ªåŠ¨, â™»ï¸ æ—¥æœ¬è‡ªåŠ¨, â™»ï¸ ç¾å›½è‡ªåŠ¨, â™»ï¸ è‡ªåŠ¨é€‰æ‹©, ğŸ‡­ğŸ‡° é¦™æ¸¯èŠ‚ç‚¹, ğŸ‡¯ğŸ‡µ æ—¥æœ¬èŠ‚ç‚¹, ğŸ‡ºğŸ‡² ç¾å›½èŠ‚ç‚¹, ğŸŒ å…¨éƒ¨èŠ‚ç‚¹, ç›´è¿]}
  - {name: ğŸ“¹ YouTube, <<: *pr}
  - {name: ğŸ€ Google, <<: *pr}
  - {name: ğŸ¤– ChatGPT, <<: *pr}
  - {name: ğŸ‘¨ğŸ¿â€ğŸ’» GitHub, <<: *pr}
  - {name: ğŸ¬ OneDrive, <<: *pr}
  - {name: ğŸªŸ Microsoft, <<: *pr}
  - {name: ğŸµ TikTok, type: select, proxies: [ğŸ”¯ æ—¥æœ¬æ•…è½¬, â™»ï¸ æ—¥æœ¬è‡ªåŠ¨, â™»ï¸ ç¾å›½è‡ªåŠ¨, ğŸ‡¯ğŸ‡µ æ—¥æœ¬èŠ‚ç‚¹, ğŸ‡ºğŸ‡² ç¾å›½èŠ‚ç‚¹, ğŸŒ å…¨éƒ¨èŠ‚ç‚¹, ç›´è¿]}
  - {name: ğŸ“² Telegram, <<: *pr}
  - {name: ğŸ¥ NETFLIX, <<: *pr}
  - {name: âœˆï¸ Speedtest, <<: *pr}
  - {name: ğŸ’¶ PayPal, <<: *pr}
  - {name: ğŸ Apple, type: select, proxies: [ç›´è¿, ğŸš€ é»˜è®¤ä»£ç†]}
  - {name: ğŸ¯ ç›´è¿, type: select, proxies: [ç›´è¿, ğŸš€ é»˜è®¤ä»£ç†]}
  - {name: ğŸŸ æ¼ç½‘ä¹‹é±¼, type: select, proxies: [ç›´è¿, ğŸš€ é»˜è®¤ä»£ç†, ğŸ”¯ é¦™æ¸¯æ•…è½¬, ğŸ”¯ æ—¥æœ¬æ•…è½¬, â™»ï¸ é¦™æ¸¯è‡ªåŠ¨, â™»ï¸ æ—¥æœ¬è‡ªåŠ¨, â™»ï¸ ç¾å›½è‡ªåŠ¨, â™»ï¸ è‡ªåŠ¨é€‰æ‹©, ğŸ‡­ğŸ‡° é¦™æ¸¯èŠ‚ç‚¹, ğŸ‡¯ğŸ‡µ æ—¥æœ¬èŠ‚ç‚¹, ğŸ‡ºğŸ‡² ç¾å›½èŠ‚ç‚¹, ğŸŒ å…¨éƒ¨èŠ‚ç‚¹]}
  - {name: ğŸ‡­ğŸ‡° é¦™æ¸¯èŠ‚ç‚¹, type: select, include-all: true, filter: "(?i)æ¸¯|hk|hongkong|hong kong"}
  - {name: ğŸ‡¯ğŸ‡µ æ—¥æœ¬èŠ‚ç‚¹, type: select, include-all: true, filter: "(?i)æ—¥|jp|japan"}
  - {name: ğŸ‡ºğŸ‡² ç¾å›½èŠ‚ç‚¹, type: select, include-all: true, filter: "(?i)ç¾|us|unitedstates|united states"}
  - {name: ğŸ”¯ é¦™æ¸¯æ•…è½¬, type: fallback, include-all: true, tolerance: 20, interval: 300, filter: "(?=.*(æ¸¯|HK|(?i)Hong))^((?!(å°|æ—¥|éŸ©|æ–°|æ·±|ç¾)).)*$"}
  - {name: ğŸ”¯ æ—¥æœ¬æ•…è½¬, type: fallback, include-all: true, tolerance: 20, interval: 300, filter: "(?=.*(æ—¥|JP|(?i)Japan))^((?!(æ¸¯|å°|éŸ©|æ–°|ç¾)).)*$" }
  - {name: â™»ï¸ é¦™æ¸¯è‡ªåŠ¨, type: url-test, include-all: true, tolerance: 20, interval: 300, filter: "(?=.*(æ¸¯|HK|(?i)Hong))^((?!(å°|æ—¥|éŸ©|æ–°|æ·±|ç¾)).)*$"}
  - {name: â™»ï¸ æ—¥æœ¬è‡ªåŠ¨, type: url-test, include-all: true, tolerance: 20, interval: 300, filter: "(?=.*(æ—¥|JP|(?i)Japan))^((?!(æ¸¯|å°|éŸ©|æ–°|ç¾)).)*$" }
  - {name: â™»ï¸ ç¾å›½è‡ªåŠ¨, type: url-test, include-all: true, tolerance: 20, interval: 300, filter: "(?=.*(ç¾|US|(?i)States|America))^((?!(æ¸¯|å°|æ—¥|éŸ©|æ–°)).)*$"}
  - {name: â™»ï¸ è‡ªåŠ¨é€‰æ‹©, type: url-test, include-all: true, tolerance: 20, interval: 300, filter: "^((?!(ç›´è¿)).)*$"}
  - {name: ğŸŒ å…¨éƒ¨èŠ‚ç‚¹, type: select, include-all: true}

# è§„åˆ™åŒ¹é…
rules:
  - DOMAIN-SUFFIX,qichiyu.com,ğŸš€ é»˜è®¤ä»£ç†
  - RULE-SET,custom_direct,ğŸ¯ ç›´è¿
  - RULE-SET,custom_proxy,ğŸš€ é»˜è®¤ä»£ç†
  - RULE-SET,private_domain, ç›´è¿
  - RULE-SET,apple_domain,ğŸ Apple
  - RULE-SET,proxylite,ğŸš€ é»˜è®¤ä»£ç†
  - RULE-SET,ai,ğŸ¤– ChatGPT
  - RULE-SET,github_domain,ğŸ‘¨ğŸ¿â€ğŸ’» GitHub
  - RULE-SET,youtube_domain,ğŸ“¹ YouTube
  - RULE-SET,google_domain,ğŸ€ Google
  - RULE-SET,onedrive_domain,ğŸ¬ OneDrive
  - RULE-SET,microsoft_domain,ğŸªŸ Microsoft
  - RULE-SET,tiktok_domain,ğŸµ TikTok
  - RULE-SET,speedtest_domain,âœˆï¸ Speedtest
  - RULE-SET,telegram_domain,ğŸ“² Telegram
  - RULE-SET,netflix_domain,ğŸ¥ NETFLIX
  - RULE-SET,paypal_domain,ğŸ’¶ PayPal
  - RULE-SET,category_game_accelerator_cn,ğŸ¯ ç›´è¿
  - RULE-SET,category_game_platforms_download,ğŸ¯ ç›´è¿
  - RULE-SET,gfw_domain,ğŸš€ é»˜è®¤ä»£ç†
  - RULE-SET,geolocation-!cn,ğŸš€ é»˜è®¤ä»£ç†
  - RULE-SET,cn_domain,ğŸ¯ ç›´è¿
  - RULE-SET,google_ip,ğŸ€ Google,no-resolve
  - RULE-SET,netflix_ip,ğŸ¥ NETFLIX,no-resolve
  - RULE-SET,telegram_ip,ğŸ“² Telegram,no-resolve
  - RULE-SET,cn_ip,ğŸ¯ ç›´è¿
  - MATCH,ğŸŸ æ¼ç½‘ä¹‹é±¼

# è§„åˆ™é›†
rule-anchor:
  ip: &ip {type: http, interval: 86400, behavior: ipcidr, format: mrs}
  domain: &domain {type: http, interval: 86400, behavior: domain, format: mrs}
  class: &class {type: http, interval: 86400, behavior: classical, format: text}
rule-providers: 
  private_domain: { <<: *domain, url: "https://raw.githubusercontent.com/MetaCubeX/meta-rules-dat/meta/geo/geosite/private.mrs"}
  proxylite: { <<: *class, url: "https://raw.githubusercontent.com/qichiyuhub/rule/refs/heads/main/proxy.list"}
  ai: {  <<: *domain, url: "https://github.com/MetaCubeX/meta-rules-dat/raw/refs/heads/meta/geo/geosite/category-ai-!cn.mrs" }
  youtube_domain: { <<: *domain, url: "https://raw.githubusercontent.com/MetaCubeX/meta-rules-dat/meta/geo/geosite/youtube.mrs"}
  google_domain: { <<: *domain, url: "https://raw.githubusercontent.com/MetaCubeX/meta-rules-dat/meta/geo/geosite/google.mrs"}
  github_domain: { <<: *domain, url: "https://raw.githubusercontent.com/MetaCubeX/meta-rules-dat/meta/geo/geosite/github.mrs"}
  telegram_domain: { <<: *domain, url: "https://raw.githubusercontent.com/MetaCubeX/meta-rules-dat/meta/geo/geosite/telegram.mrs"}
  netflix_domain: { <<: *domain, url: "https://raw.githubusercontent.com/MetaCubeX/meta-rules-dat/meta/geo/geosite/netflix.mrs"}
  paypal_domain: { <<: *domain, url: "https://raw.githubusercontent.com/MetaCubeX/meta-rules-dat/meta/geo/geosite/paypal.mrs"}
  onedrive_domain: { <<: *domain, url: "https://raw.githubusercontent.com/MetaCubeX/meta-rules-dat/meta/geo/geosite/onedrive.mrs"}
  microsoft_domain: { <<: *domain, url: "https://raw.githubusercontent.com/MetaCubeX/meta-rules-dat/meta/geo/geosite/microsoft.mrs"}
  apple_domain: { <<: *domain, url: "https://raw.githubusercontent.com/MetaCubeX/meta-rules-dat/meta/geo/geosite/apple-cn.mrs"}
  speedtest_domain: { <<: *domain, url: "https://raw.githubusercontent.com/MetaCubeX/meta-rules-dat/meta/geo/geosite/ookla-speedtest.mrs"}
  tiktok_domain: { <<: *domain, url: "https://raw.githubusercontent.com/MetaCubeX/meta-rules-dat/meta/geo/geosite/tiktok.mrs"}
  category_game_accelerator_cn: { <<: *domain, url: "https://raw.githubusercontent.com/MetaCubeX/meta-rules-dat/meta/geo/geosite/category-game-accelerator-cn.mrs"}
  category_game_platforms_download: { <<: *domain, url: "https://raw.githubusercontent.com/MetaCubeX/meta-rules-dat/meta/geo/geosite/category-game-platforms-download.mrs"}
  category_ntp: { <<: *domain, url: "https://raw.githubusercontent.com/MetaCubeX/meta-rules-dat/meta/geo/geosite/category-ntp.mrs"}
  gfw_domain: { <<: *domain, url: "https://raw.githubusercontent.com/MetaCubeX/meta-rules-dat/meta/geo/geosite/gfw.mrs"}
  geolocation-!cn: { <<: *domain, url: "https://raw.githubusercontent.com/MetaCubeX/meta-rules-dat/meta/geo/geosite/geolocation-!cn.mrs"}
  cn_domain: { <<: *domain, url: "https://raw.githubusercontent.com/MetaCubeX/meta-rules-dat/meta/geo/geosite/cn.mrs"}
  cn_ip: { <<: *ip, url: "https://raw.githubusercontent.com/MetaCubeX/meta-rules-dat/meta/geo/geoip/cn.mrs"}
  google_ip: { <<: *ip, url: "https://raw.githubusercontent.com/MetaCubeX/meta-rules-dat/meta/geo/geoip/google.mrs"}
  telegram_ip: { <<: *ip, url: "https://raw.githubusercontent.com/MetaCubeX/meta-rules-dat/meta/geo/geoip/telegram.mrs"}
  netflix_ip: { <<: *ip, url: "https://raw.githubusercontent.com/MetaCubeX/meta-rules-dat/meta/geo/geoip/netflix.mrs"}
  fakeip_filter:
    type: inline
    behavior: classical
    payload:
      - DOMAIN-KEYWORD,ipv6
      - DOMAIN-SUFFIX,lvxj11.top
      - DOMAIN-SUFFIX,msftconnecttest.com
      - DOMAIN-SUFFIX,msftncsi.com
  custom_direct:
    type: inline
    behavior: classical
    payload:
      - DOMAIN-SUFFIX,lvxj11.top
      - DOMAIN-SUFFIX,test-ipv6.com
      - DOMAIN-REGEX,^cache.*steamcontent\.com$
  custom_proxy:
    type: inline
    behavior: classical
    payload:
      - DOMAIN-SUFFIX,ixsystems.com